### ISSUE TITLE
Battle prep saves not supported yet

### ISSUE THREAD

**Issue by Soaprman** [Soaprman/FEFTwiddler#7]
I kind of forgot this was a thing, and I read recently that the structure changes if you save on battle prep. It probably doesn't work with FEFTwiddler!

The near-term (and maybe only-term) fix will probably be to detect whether a save is a battle prep save, and if it is, tell the user to save in My Castle instead, since it's way less work to back out and save in a different spot than it is to program around another byte structure...

**Comment by DeathChaos25** [comment]
This is because in the prep screen, the save also stores unit data for all of the currently spawned units within the map.

When the map first loads, it loads the data from GameData/Dispos and it spawns the units it needs to, then when the player saves, the data is then stored into the player's save data and the game would then load the dispos data from the save as opposed to the rom, this would also mean that in theory, you could spawn new units on the map via save hacking.

**Comment by Soaprman** [comment]
Oh wow, that actually sounds pretty interesting, and it makes me kind of enthusiastic about making battle prep saves work. Thanks for the info!

**Comment by Soaprman** [comment]
Looks like the enemies aren't in the battle prep screen saves to me. They're probably in the mid-battle bookmark saves, though, which I'm not even sure how to extract yet (they may be saved on the SD card).

At any rate, this actually didn't need many changes.
